#!/usr/bin/env bash
# =====================================================================
#  مَرصَد — VPS Bootstrap Script (Ubuntu 22.04 / Debian 12)
# =====================================================================
#  شغّله كـ root على VPS نظيف:
#     curl -fsSL https://raw.githubusercontent.com/AsemAbbas/facebook_scraper/main/deploy/install.sh | sudo bash
#     # أو
#     sudo bash deploy/install.sh
#
#  ماذا يفعل؟
#   1. ينشئ مستخدم نظام 'marsad' (non-login)
#   2. يثبّت Python 3.11+, MariaDB, Nginx, Git
#   3. ينسخ المشروع إلى /opt/marsad
#   4. ينشئ virtualenv + يثبّت الحزم
#   5. ينزّل Chromium لـ Playwright مع dependencies النظام
#   6. يسأل عن بيانات DB ويُنشئ .env
#   7. يُنشئ DB + user في MariaDB
#   8. يُثبّت systemd service ويفعّله
#   9. ينشر nginx config (تحتاج تعدّل domain وتُشغّل certbot بعدين)
# =====================================================================

set -euo pipefail

# ---------- Colors ----------
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No color

log()  { echo -e "${GREEN}[مَرصَد]${NC} $*"; }
warn() { echo -e "${YELLOW}[تحذير]${NC} $*"; }
err()  { echo -e "${RED}[خطأ]${NC} $*" >&2; }
die()  { err "$*"; exit 1; }

# ---------- Pre-checks ----------
[[ $EUID -eq 0 ]] || die "يجب تشغيل السكريبت كـ root (استخدم sudo)."

OS_ID=$(. /etc/os-release && echo "$ID")
case "$OS_ID" in
    ubuntu|debian) ;;
    *) die "هذا السكريبت يدعم Ubuntu/Debian فقط. للأنظمة الأخرى راجع VPS_DEPLOYMENT.md يدوياً." ;;
esac

INSTALL_DIR=${INSTALL_DIR:-/opt/marsad}
SERVICE_USER=${SERVICE_USER:-marsad}
REPO_URL=${REPO_URL:-"https://github.com/AsemAbbas/facebook_scraper.git"}

# ---------- 1. System packages ----------
log "تثبيت الحزم الأساسية..."
export DEBIAN_FRONTEND=noninteractive
apt update -y
apt install -y \
    python3 python3-venv python3-pip python3-dev \
    mariadb-server \
    nginx \
    git curl wget \
    build-essential \
    ca-certificates \
    ufw

# ---------- 2. Service user ----------
if ! id "$SERVICE_USER" &>/dev/null; then
    log "إنشاء مستخدم النظام '$SERVICE_USER'..."
    useradd --system --home "$INSTALL_DIR" --shell /usr/sbin/nologin "$SERVICE_USER"
else
    log "المستخدم '$SERVICE_USER' موجود بالفعل."
fi

# ---------- 3. Clone / update code ----------
if [[ -d "$INSTALL_DIR/.git" ]]; then
    log "المشروع موجود - تحديث..."
    cd "$INSTALL_DIR"
    sudo -u "$SERVICE_USER" git pull || warn "فشل git pull - تابع يدوياً"
else
    log "استنساخ المشروع إلى $INSTALL_DIR ..."
    mkdir -p "$INSTALL_DIR"
    chown "$SERVICE_USER:$SERVICE_USER" "$INSTALL_DIR"
    sudo -u "$SERVICE_USER" git clone "$REPO_URL" "$INSTALL_DIR"
fi

cd "$INSTALL_DIR"

# ---------- 4. Python venv + deps ----------
log "إنشاء Python virtualenv..."
sudo -u "$SERVICE_USER" python3 -m venv venv
sudo -u "$SERVICE_USER" ./venv/bin/pip install --upgrade pip wheel
sudo -u "$SERVICE_USER" ./venv/bin/pip install -r requirements.txt

# ---------- 5. Playwright chromium ----------
log "تثبيت Chromium لـ Playwright (قد يستغرق دقائق)..."
# System deps must be installed as root
./venv/bin/playwright install-deps chromium || warn "فشل install-deps - قد يتسبب بمشاكل مع Playwright"
# The browser itself installs in the service user's home/cache
sudo -u "$SERVICE_USER" ./venv/bin/playwright install chromium

# ---------- 6. MariaDB setup ----------
systemctl enable --now mariadb

if [[ ! -f "$INSTALL_DIR/.env" ]]; then
    log "إعداد قاعدة البيانات..."
    DB_NAME=${DB_NAME:-marsad}
    DB_USER=${DB_USER:-marsad}
    DB_PASS=$(openssl rand -base64 24 | tr -d '=+/' | head -c 24)

    mysql <<EOF
CREATE DATABASE IF NOT EXISTS \`$DB_NAME\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASS';
GRANT ALL PRIVILEGES ON \`$DB_NAME\`.* TO '$DB_USER'@'localhost';
FLUSH PRIVILEGES;
EOF

    log "إنشاء .env..."
    cat > "$INSTALL_DIR/.env" <<EOF
# Auto-generated by install.sh - $(date -Iseconds)
MARSAD_DB_HOST=localhost
MARSAD_DB_PORT=3306
MARSAD_DB_NAME=$DB_NAME
MARSAD_DB_USER=$DB_USER
MARSAD_DB_PASSWORD=$DB_PASS

HOST=127.0.0.1
PORT=5050
NO_BROWSER=1
EOF
    chmod 600 "$INSTALL_DIR/.env"
    chown "$SERVICE_USER:$SERVICE_USER" "$INSTALL_DIR/.env"

    log "تم إنشاء DB بالمعلومات التالية (محفوظة في $INSTALL_DIR/.env):"
    echo "   DB:     $DB_NAME"
    echo "   USER:   $DB_USER"
    echo "   PASS:   $DB_PASS"
else
    log ".env موجود بالفعل - تخطي إنشاء DB (عدّل يدوياً لو احتجت)."
fi

# ---------- 7. Log + data dirs ----------
mkdir -p /var/log/marsad "$INSTALL_DIR/logs" "$INSTALL_DIR/database"
chown -R "$SERVICE_USER:$SERVICE_USER" /var/log/marsad "$INSTALL_DIR/logs" "$INSTALL_DIR/database"

# ---------- 8. systemd service ----------
log "تثبيت systemd service..."
cp "$INSTALL_DIR/deploy/marsad.service" /etc/systemd/system/marsad.service
systemctl daemon-reload
systemctl enable marsad
systemctl restart marsad
sleep 3
if systemctl is-active --quiet marsad; then
    log "✅ خدمة marsad تعمل. تابع السجل بـ: journalctl -u marsad -f"
else
    err "فشل تشغيل الخدمة. فحص السجل:"
    journalctl -u marsad -n 50 --no-pager
    die "تأكد من الأخطاء أعلاه وأعد المحاولة."
fi

# ---------- 9. Nginx ----------
if [[ ! -f /etc/nginx/sites-available/marsad ]]; then
    log "نشر nginx config (تحتاج تعديل domain لاحقاً)..."
    cp "$INSTALL_DIR/deploy/nginx.conf" /etc/nginx/sites-available/marsad
    ln -sf /etc/nginx/sites-available/marsad /etc/nginx/sites-enabled/marsad
    # Remove default site to avoid conflicts
    rm -f /etc/nginx/sites-enabled/default
    if nginx -t 2>/dev/null; then
        systemctl reload nginx
    else
        warn "nginx config تحتاج تعديل قبل ما تشتغل — راجع /etc/nginx/sites-available/marsad"
    fi
else
    log "nginx config موجود - تخطي."
fi

# ---------- 10. Firewall ----------
log "ضبط firewall (UFW)..."
ufw allow OpenSSH
ufw allow 'Nginx Full'
ufw --force enable || true

# ---------- Done ----------
cat <<'EOF'

============================================================
🎉 تم التثبيت!

الخطوات التالية:
  1. عدّل nginx config:  /etc/nginx/sites-available/marsad
     غيّر 'marsad.example.com' إلى domain حقيقي
     sudo systemctl reload nginx

  2. ثبّت شهادة SSL:
     sudo apt install -y certbot python3-certbot-nginx
     sudo certbot --nginx -d marsad.example.com

  3. افتح الموقع → سجّل أول حساب admin.

  4. فحص الصحة:
     sudo systemctl status marsad
     sudo journalctl -u marsad -f
     curl http://127.0.0.1:5050/healthz

============================================================
EOF
